<a href="https://colab.research.google.com/github/sudiptamuk/tensorflow/blob/main/Tf_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
tf1 = tf.constant([[1,2,3,4], [5,6,7,8]])
tf2 = tf.constant([[2,3,4,5], [4,3,2,1]])
tf1, tf2

(<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[2, 3, 4, 5],
        [4, 3, 2, 1]], dtype=int32)>)

In [5]:
tf.matmul(tf1, tf2)

InvalidArgumentError: ignored

In [6]:
tf.matmul(tf.transpose(tf1), tf2)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[22, 18, 14, 10],
       [28, 24, 20, 16],
       [34, 30, 26, 22],
       [40, 36, 32, 28]], dtype=int32)>

In [7]:
tf.matmul(tf1, tf.transpose(tf2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 20],
       [96, 60]], dtype=int32)>

In [8]:
tf.transpose(tf2)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 4],
       [3, 3],
       [4, 2],
       [5, 1]], dtype=int32)>

In [13]:
tf.reshape(tf1, shape=[4,2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>